# Copyright (c) 2026, Nirmaan (Stratos Infra Technologies Pvt. Ltd.) and contributors
# For license information, please see license.txt
"""
BoQ category rule runner -- pure-Python, framework-free (NO frappe imports).

Given one committed BoQ Line Item's text context (its description, its parent_node
ancestor chain, and any attached notes), score it against the electrical category
rule set and return an EXPLAINABLE classification: a category, a 0-1 confidence,
a band, the exact rules that fired, and a human-readable reason.

This module is RULES ONLY. There are no network/AI/DB calls and no I/O in the
hot path -- the JSON assets are read once (lazily, cached) via load_ruleset().
The prompt-2 harness calls classify_line() per line and may also run an AI pass;
the AI pass is NOT here.

------------------------------------------------------------------------------
THE SCORING MODEL (all knobs live in scoring.json -- nothing here is hardcoded)
------------------------------------------------------------------------------
A "rule" is a single signal: an item_keyword (matched against description+notes),
an ancestor (matched against the ancestor chain), or an exclusion (a false-friend
guard). Each positive rule carries a weight in 0-1 and a `plain` explanation.

For one line:
  1. SCORE   Every positive rule whose tokens match contributes its weight to its
             category. Weights for the same category are summed.
  2. AGREE   If a category is supported by >=2 DISTINCT signal_types (e.g. an
             item_keyword AND an ancestor agree), add scoring.agreement_bonus once.
  3. CAP     Clamp each category score to scoring.cap (1.0).
  4. EXCLUDE If any exclusion token for a category is present (from an `exclusion`
             rule OR an `exclude_if` on any of that category's rules), that
             category's score is ZEROED (the false-friend guard, e.g. an "LED
             panel" is a light fixture, not a switchgear Panel).
  5. PICK    The highest-scoring category wins; the second is the runner-up.
  6. CONFLICT If the runner-up is a genuine competitor (its score >=
             top * scoring.conflict_margin), multiply the top score by
             (1 - scoring.conflict_penalty). This pushes a contested two-way down
             a band and the reason names both candidates.
  7. BAND    Final top score -> band via scoring.bands:
             HIGH >= high; MED >= med; LOW > 0; ABSTAIN == 0 -> BLANK category ("").

To TUNE: edit scoring.json (thresholds/bonus/penalty) and rules_electrical.json
(weights/tokens). Do not edit this file to change behaviour -- it only executes
the model the data describes.
"""
from __future__ import annotations

import json
import os
import re
from functools import lru_cache
from typing import Any

_HERE = os.path.dirname(os.path.abspath(__file__))


# ---------------------------------------------------------------------------
# Asset loading (explicit, cached; the only file I/O in the module)
# ---------------------------------------------------------------------------

def _read_json(filename: str) -> dict:
    with open(os.path.join(_HERE, filename), encoding="utf-8") as fh:
        return json.load(fh)


@lru_cache(maxsize=None)
def load_ruleset(discipline: str = "Electrical") -> dict:
    """Load + cache the category/rule/scoring assets for a discipline.

    Returns a dict with keys: categories (list), rules (list), scoring (dict),
    and a few derived lookups. Cached so repeated classify_line() calls do no I/O.
    Currently only 'Electrical' is shipped; the signature is discipline-aware so
    other disciplines can drop in <disc>-suffixed asset files later.
    """
    if discipline != "Electrical":
        raise ValueError(f"no category ruleset shipped for discipline {discipline!r}")
    categories = _read_json("categories_electrical.json")["categories"]
    rules = _read_json("rules_electrical.json")["rules"]
    scoring = _read_json("scoring.json")

    # Per-category exclusion guards (false-friend suppressors). Two kinds:
    #   token  -- whole-token match (inline `exclude_if` on any rule, and
    #             `exclusion`-type rules whose match_mode is not 'regex').
    #   regex  -- `exclusion`-type rules with match_mode 'regex' (e.g. the
    #             'wiring for ... point(s)' guard that needs a span pattern).
    # Either kind firing ZEROES that category's score.
    exclude_tokens_by_cat: dict[str, list[str]] = {}
    exclude_regex_by_cat: dict[str, list[str]] = {}
    for r in rules:
        cat = r["category_id"]
        if r.get("signal_type") == "exclusion":
            if r.get("match_mode") == "regex":
                exclude_regex_by_cat.setdefault(cat, []).extend(r.get("match", []))
            else:
                exclude_tokens_by_cat.setdefault(cat, []).extend(r.get("match", []))
        for tok in r.get("exclude_if", []) or []:
            exclude_tokens_by_cat.setdefault(cat, []).append(tok)

    return {
        "categories": categories,
        "rules": rules,
        "scoring": scoring,
        "exclude_tokens_by_cat": {k: tuple(v) for k, v in exclude_tokens_by_cat.items()},
        "exclude_regex_by_cat": {k: tuple(v) for k, v in exclude_regex_by_cat.items()},
        "name_by_cat": {c["category_id"]: c["name"] for c in categories},
    }


# ---------------------------------------------------------------------------
# Matching primitives (deterministic, pure)
# ---------------------------------------------------------------------------

def _norm(text: str | None) -> str:
    """Lower-case + collapse whitespace. Deterministic, side-effect free."""
    if not text:
        return ""
    return re.sub(r"\s+", " ", str(text).lower())


@lru_cache(maxsize=8192)
def _token_re(token: str):
    """Compile (cached) a whole-token matcher for `token`.

    A token matches only when it is NOT flanked by another alphanumeric char, so
    short tokens do not match inside longer words: 'mcc' must not fire on 'mccb',
    'panel' must not fire on 'patch panel', 'dia' must not fire on 'media'. The
    boundary is alphanumeric-aware (not Python's \\b) so tokens with internal
    punctuation/spaces ('sq.mm', 'cable tray', 'c-channel') still match cleanly.

    CONSERVATIVE PLURAL-AWARENESS: a singular token also matches a regular s/es
    plural of its FINAL word in the text -- so 'junction box' hits 'junction boxes',
    'cable tray' hits 'cable trays', 'socket' hits 'sockets'. This is the pattern
    fix (generic over tokens, no category or plural list hardcoded). GUARDED against
    false positives: the optional suffix is added only when the final word is >= 3
    chars and does NOT already end in 's' -- so words like gas/bus/class/glass/status/
    access/process/plus/cross (and 2-char units like 'mm') are never mis-stripped, and
    an already-plural token (ending in 's', e.g. 'light points', 'socket outlets') is
    left exact. The suffix is OPTIONAL so the singular still matches (backward-compatible).
    Applies wherever _token_re is used: item_keyword + ancestor + exclusion matching.
    """
    body = re.escape(token)
    last = token.split(" ")[-1] if token else token
    if len(last) >= 3 and not last.endswith("s"):
        body += r"(?:es|s)?"
    return re.compile(r"(?<![a-z0-9])" + body + r"(?![a-z0-9])")


def _contains(token: str, blob: str) -> bool:
    t = _norm(token)
    return bool(t) and _token_re(t).search(blob) is not None


def _tokens_present(tokens: list[str], mode: str, blob: str) -> bool:
    """True if any token matches `blob` under the given match_mode.

    any_token / phrase -> whole-token match (see _token_re) over the normalised blob.
    regex             -> re.search of each pattern (already case-insensitive blob).
    """
    if not blob:
        return False
    if mode == "regex":
        return any(re.search(p, blob, re.IGNORECASE) for p in tokens)
    return any(_contains(t, blob) for t in tokens)


def _excluded(category_id: str, ruleset: dict, desc_blob: str) -> bool:
    """True if a false-friend exclusion guard for this category fires.

    Token guards use whole-token matching; regex guards use re.search (for
    span patterns like 'wiring for ... point(s)'). Either kind firing zeroes
    the category.
    """
    toks = ruleset["exclude_tokens_by_cat"].get(category_id, ())
    if any(_contains(t, desc_blob) for t in toks):
        return True
    pats = ruleset["exclude_regex_by_cat"].get(category_id, ())
    return any(re.search(p, desc_blob, re.IGNORECASE) for p in pats)


def _infer_from_ancestors(anc_blob: str, ruleset: dict,
                          anc_headers_blob: str | None = None) -> dict:
    """FIX 4 helper: score categories using the ANCESTOR text alone.

    Runs both item_keyword and ancestor rules against the ancestor blob (so a
    parent section/line that itself names a category is detected), sums weights
    per category, and zeroes any category whose exclusion guard fires on the
    ancestor text. Used only when the line itself ABSTAINS, to let a fragment
    row inherit its parent section's category. Returns {category_id: score}.

    v2.1 tuning2: headers_only ancestor rules (EARTH-ANC) match the header blob.
    """
    hblob = anc_headers_blob if anc_headers_blob is not None else anc_blob
    sums: dict[str, float] = {}
    for r in ruleset["rules"]:
        stype = r.get("signal_type")
        if stype not in ("item_keyword", "ancestor"):
            continue
        blob = hblob if (stype == "ancestor" and r.get("headers_only")) else anc_blob
        if _tokens_present(r["match"], r.get("match_mode", "any_token"), blob):
            sums[r["category_id"]] = sums.get(r["category_id"], 0.0) + float(r["weight"])
    return {c: v for c, v in sums.items() if v > 0 and not _excluded(c, ruleset, anc_blob)}


# ---------------------------------------------------------------------------
# v2.1 tuning2: dimension-count geometry signals (conduit-dia / junction-box W x H x D)
# ---------------------------------------------------------------------------
# A bare size leaf under a raceway/conduit section carries no category word; the DIMENSION
# COUNT is the signal a human uses: 1 number + 'dia' -> round conduit; 3 numbers W x H x D
# (a real box depth 40-600mm, tray-naming words excluded) -> junction-box enclosure; 2
# numbers W x H -> tray. Applied as an OVERRIDE on a winning cabletray/earthing/blank result
# under the right ancestor context, so it never overrides a strong direct keyword signal.

_GEOM_3NUM = re.compile(r"(\d+)\s*(?:mm)?\s*[x*X]\s*(\d+)\s*(?:mm)?\s*[x*X]\s*(\d+)")
_GEOM_2NUM = re.compile(r"\d\s*(?:mm)?\s*[x*X]\s*\d")
# tray-naming exclusions ONLY -- deliberately NOT thick/swg/gauge: a junction box may state
# its gauge ('460x460x50mm 16 SWG'); the depth threshold (not a word) splits box vs thickness.
_GEOM_TRAY_WORDS = ("trunking", "basket", "cable tray", " tray", "ladder", "perforated", "trough")
_GEOM_BOX_CTX = ("raceway", "cable tray", "trunking", "junction", "pull box", "draw box",
                 "wire way", "wireway", "ladder")


def _is_box(description: str) -> bool:
    """A three-dimension W x H x D enclosure size with a real box depth (40-600mm), not a tray."""
    d = (description or "").lower()
    m = _GEOM_3NUM.search(description or "")
    if not m or any(w in d for w in _GEOM_TRAY_WORDS):
        return False
    return 40 <= int(m.group(3)) <= 600 and ("mm" in d or "size" in d or "depth" in d)


def _is_conduit_dia(description: str) -> bool:
    """A single-diameter round conduit size ('25mm dia') -- one dimension + 'dia', not a W x H tray."""
    d = (description or "").lower()
    if "dia" not in d and "diameter" not in d:
        return False
    if _GEOM_2NUM.search(description or ""):
        return False
    return bool(re.search(r"\d", description or ""))


def _anc_box_ctx(anc_blob: str) -> bool:
    return any(k in anc_blob for k in _GEOM_BOX_CTX)


def _anc_conduit(anc_blob: str) -> bool:
    return "conduit" in anc_blob


def _geometry_override(category_id: str, description: str, anc_blob: str):
    """Return (new_category, reason) if a geometry signal fires, else (category_id, None).
    Order: junction-box (3-dim) then conduit (1-dim dia); mutually exclusive by dimension
    count. Fires only on a cabletray_raceway/earthing/blank winner under the right context."""
    if category_id in ("cabletray_raceway", "earthing", ""):
        if _is_box(description) and _anc_box_ctx(anc_blob):
            return "junction_box_raceway", (
                "Geometry: a three-dimension W x H x D enclosure size (depth 40-600mm) under a "
                "raceway/box section -- this is a junction box, not a tray run.")
        if _is_conduit_dia(description) and _anc_conduit(anc_blob):
            return "conduit_piping", (
                "Geometry: a single-diameter (Xmm dia) round conduit size under a conduit "
                "section -- this is conduit, not a tray.")
    return category_id, None


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------

def classify_line(
    description: str,
    ancestor_texts: list[str] | None = None,
    notes: list[str] | None = None,
    *,
    discipline: str = "Electrical",
    ancestor_headers: list[str] | None = None,
) -> dict:
    """Classify ONE committed BoQ line into an electrical pricing category.

    Parameters
    ----------
    description : str
        The line item's own description text.
    ancestor_texts : list[str]
        The parent_node ancestor chain (preamble/line-item descriptions from the
        line up to the root). Pass the FULL chain so ancestor (section-header)
        rules can fire and so child sub-lines inherit their parent's context.
    notes : list[str]
        Attached notes for the line (attached_notes / append_notes values),
        treated as part of the line's own text for item_keyword/exclusion matching.
    discipline : str, keyword-only, default "Electrical"
        Which category ruleset to load.
    ancestor_headers : list[str] | None, keyword-only
        The ancestor chain's DESCRIPTIONS / section headers ONLY (no notes), parallel to
        ancestor_texts. Rules flagged ``headers_only`` (e.g. EARTH-ANC) match against this,
        so an incidental keyword in an ancestor NOTE ('the channels shall be earthed') does
        not false-fire a section-header rule. When None, headers_only rules fall back to the
        full ancestor blob (backward compatible for callers that do not pass headers).

    Returns
    -------
    dict with keys:
      category_id   : str  -- winning category, or "" (blank) on ABSTAIN
      score         : float in [0,1] -- the (post-conflict) confidence of the winner
      band          : "HIGH" | "MED" | "LOW" | "ABSTAIN"
      signals_fired : list of {rule_id, signal_type, category_id, weight, plain}
      reason        : str  -- human-readable; composed from fired rules' `plain`,
                      and for contested results states the competing category
      runner_up     : {category_id, score} | None  -- the conflict candidate
      all_scores    : {category_id: float} -- full per-category breakdown (tuning)

    Deterministic and side-effect free: the same inputs always return the same
    output, and nothing outside the returned dict is mutated.
    """
    ruleset = load_ruleset(discipline)
    rules = ruleset["rules"]
    scoring = ruleset["scoring"]
    cap = scoring["cap"]
    bands = scoring["bands"]
    abstain_category_id = scoring["novel_category_id"]

    desc_blob = _norm((description or "") + " " + " ".join(notes or []))
    anc_blob = _norm(" ".join(ancestor_texts or []))
    # v2.1 tuning2: ancestor HEADERS (descriptions) only, for headers_only rules (EARTH-ANC).
    # Falls back to the full ancestor blob when headers are not supplied (backward compatible).
    anc_headers_blob = _norm(" ".join(ancestor_headers)) if ancestor_headers is not None else anc_blob

    # 1-2: gather fired rules per category, summing weights + tracking signal types
    fired: list[dict] = []
    sum_by_cat: dict[str, float] = {}
    sigtypes_by_cat: dict[str, set] = {}
    for r in rules:
        stype = r.get("signal_type")
        if stype not in ("item_keyword", "ancestor"):
            continue  # exclusion rules are handled in step 4, not scored positively
        if stype == "item_keyword":
            blob = desc_blob
        else:  # ancestor: headers_only rules see the header blob, others the full blob
            blob = anc_headers_blob if r.get("headers_only") else anc_blob
        if _tokens_present(r["match"], r.get("match_mode", "any_token"), blob):
            cat = r["category_id"]
            sum_by_cat[cat] = sum_by_cat.get(cat, 0.0) + float(r["weight"])
            sigtypes_by_cat.setdefault(cat, set()).add(stype)
            fired.append({
                "rule_id": r["rule_id"],
                "signal_type": stype,
                "category_id": cat,
                "weight": float(r["weight"]),
                "plain": r.get("plain", ""),
            })

    # 2-4: agreement bonus, cap, exclusions
    scores: dict[str, float] = {}
    for cat, raw in sum_by_cat.items():
        s = raw
        if len(sigtypes_by_cat.get(cat, ())) >= 2:
            s += scoring["agreement_bonus"]
        s = min(cap, s)
        if _excluded(cat, ruleset, desc_blob):
            s = 0.0
        scores[cat] = round(s, 6)

    name_by_cat = ruleset["name_by_cat"]

    # 5: pick top + runner-up among positive scores
    positive = {c: v for c, v in scores.items() if v > 0}
    if not positive:
        # FIX 4: fragment inheritance. The line itself ABSTAINED -- before routing
        # to review (blank), see whether its ancestor chain alone resolves to EXACTLY ONE
        # dominant category. If so, inherit it DOWN-WEIGHTED (never HIGH).
        inh = _infer_from_ancestors(anc_blob, ruleset, anc_headers_blob)
        if inh:
            ranked_inh = sorted(inh.items(), key=lambda kv: (-kv[1], kv[0]))
            top_c, top_v = ranked_inh[0]
            second_v = ranked_inh[1][1] if len(ranked_inh) > 1 else 0.0
            if top_v > second_v:  # strictly one dominant ancestor category
                inh_score = round(min(scoring["inheritance_cap"],
                                      top_v * scoring["inheritance_weight"]), 6)
                if inh_score > 0:
                    inh_band = "HIGH" if inh_score >= bands["high"] else (
                        "MED" if inh_score >= bands["med"] else "LOW")
                    inh_reason = (f"no direct signal on the line; inherited from parent "
                                  f"section: {name_by_cat.get(top_c, top_c)} -- review.")
                    geo_c, geo_r = _geometry_override(top_c, description, anc_blob)
                    if geo_c != top_c:
                        top_c, inh_reason = geo_c, geo_r
                    return {
                        "category_id": top_c,
                        "score": inh_score,
                        "band": inh_band,
                        "signals_fired": [],
                        "reason": inh_reason,
                        "runner_up": None,
                        "all_scores": scores,
                    }
        return {
            "category_id": abstain_category_id,
            "score": 0.0,
            "band": "ABSTAIN",
            "signals_fired": [],
            "reason": "no category signal matched; routed to review (blank).",
            "runner_up": None,
            "all_scores": scores,
        }

    # FIX 5: rank with a tiny bonus for categories carrying a DIRECT (item_keyword)
    # signal, so a near-tie resolves toward what the line itself names over an
    # ancestor-only competitor. The bonus affects ORDERING only -- reported scores
    # are unchanged (top_score/runner are read from `scores`).
    direct_cats = {f["category_id"] for f in fired if f["signal_type"] == "item_keyword"}
    direct_bonus = scoring.get("direct_signal_bonus", 0.0)

    def _rank_key(kv):
        cat, sc = kv
        eff = sc + (direct_bonus if cat in direct_cats else 0.0)
        return (-eff, cat)

    ranked = sorted(positive.items(), key=_rank_key)
    top_cat, top_score = ranked[0]
    runner = ranked[1] if len(ranked) > 1 else None

    # 6: conflict penalty if the runner-up is a genuine competitor
    runner_up_out = None
    contested = False
    if runner and runner[1] >= top_score * scoring["conflict_margin"]:
        contested = True
        top_score = round(top_score * (1.0 - scoring["conflict_penalty"]), 6)
        runner_up_out = {"category_id": runner[0], "score": runner[1]}

    # 7: band
    if top_score >= bands["high"]:
        band = "HIGH"
    elif top_score >= bands["med"]:
        band = "MED"
    else:
        band = "LOW"

    # reason: compose the winning category's fired `plain` strings
    top_plains = [f["plain"] for f in fired if f["category_id"] == top_cat and f["plain"]]
    reason = " ".join(top_plains) if top_plains else f"matched {name_by_cat.get(top_cat, top_cat)}."
    if contested and runner_up_out:
        reason += (
            f" Signal is contested: this could also be "
            f"{name_by_cat.get(runner[0], runner[0])} -- review."
        )

    # v2.1 tuning2: dimension-count geometry override (last, on the winning category only).
    geo_cat, geo_reason = _geometry_override(top_cat, description, anc_blob)
    if geo_cat != top_cat:
        top_cat, reason, runner_up_out = geo_cat, geo_reason, None

    return {
        "category_id": top_cat,
        "score": top_score,
        "band": band,
        "signals_fired": [f for f in fired if f["category_id"] == top_cat],
        "reason": reason,
        "runner_up": runner_up_out,
        "all_scores": scores,
    }
