# Copyright (c) 2026, Nirmaan (Stratos Infra Technologies Pvt. Ltd.) and contributors
# For license information, please see license.txt
"""
BoQ category rule runner -- pure-Python, framework-free (NO frappe imports).

Given one committed BoQ Line Item's text context (its description, its parent_node
ancestor chain, and any attached notes), score it against the electrical category
rule set and return an EXPLAINABLE classification: a category, a 0-1 confidence,
a band, the exact rules that fired, and a human-readable reason.

This module is RULES ONLY. There are no network/AI/DB calls and no I/O in the
hot path -- the JSON assets are read once (lazily, cached) via load_ruleset().
The prompt-2 harness calls classify_line() per line and may also run an AI pass;
the AI pass is NOT here.

------------------------------------------------------------------------------
THE SCORING MODEL (all knobs live in scoring.json -- nothing here is hardcoded)
------------------------------------------------------------------------------
A "rule" is a single signal: an item_keyword (matched against description+notes),
an ancestor (matched against the ancestor chain), or an exclusion (a false-friend
guard). Each positive rule carries a weight in 0-1 and a `plain` explanation.

For one line:
  1. SCORE   Every positive rule whose tokens match contributes its weight to its
             category. Weights for the same category are summed.
  2. AGREE   If a category is supported by >=2 DISTINCT signal_types (e.g. an
             item_keyword AND an ancestor agree), add scoring.agreement_bonus once.
  3. CAP     Clamp each category score to scoring.cap (1.0).
  4. EXCLUDE If any exclusion token for a category is present (from an `exclusion`
             rule OR an `exclude_if` on any of that category's rules), that
             category's score is ZEROED (the false-friend guard, e.g. an "LED
             panel" is a light fixture, not a switchgear Panel).
  5. PICK    The highest-scoring category wins; the second is the runner-up.
  6. CONFLICT If the runner-up is a genuine competitor (its score >=
             top * scoring.conflict_margin), multiply the top score by
             (1 - scoring.conflict_penalty). This pushes a contested two-way down
             a band and the reason names both candidates.
  7. BAND    Final top score -> band via scoring.bands:
             HIGH >= high; MED >= med; LOW > 0; ABSTAIN == 0 -> category 'novel'.

To TUNE: edit scoring.json (thresholds/bonus/penalty) and rules_electrical.json
(weights/tokens). Do not edit this file to change behaviour -- it only executes
the model the data describes.
"""
from __future__ import annotations

import json
import os
import re
from functools import lru_cache
from typing import Any

_HERE = os.path.dirname(os.path.abspath(__file__))


# ---------------------------------------------------------------------------
# Asset loading (explicit, cached; the only file I/O in the module)
# ---------------------------------------------------------------------------

def _read_json(filename: str) -> dict:
    with open(os.path.join(_HERE, filename), encoding="utf-8") as fh:
        return json.load(fh)


@lru_cache(maxsize=None)
def load_ruleset(discipline: str = "Electrical") -> dict:
    """Load + cache the category/rule/scoring assets for a discipline.

    Returns a dict with keys: categories (list), rules (list), scoring (dict),
    and a few derived lookups. Cached so repeated classify_line() calls do no I/O.
    Currently only 'Electrical' is shipped; the signature is discipline-aware so
    other disciplines can drop in <disc>-suffixed asset files later.
    """
    if discipline != "Electrical":
        raise ValueError(f"no category ruleset shipped for discipline {discipline!r}")
    categories = _read_json("categories_electrical.json")["categories"]
    rules = _read_json("rules_electrical.json")["rules"]
    scoring = _read_json("scoring.json")

    # Per-category exclusion tokens: union of `exclusion`-rule matches and any
    # rule's inline `exclude_if`.
    exclude_by_cat: dict[str, list[str]] = {}
    for r in rules:
        cat = r["category_id"]
        if r.get("signal_type") == "exclusion":
            exclude_by_cat.setdefault(cat, []).extend(r.get("match", []))
        for tok in r.get("exclude_if", []) or []:
            exclude_by_cat.setdefault(cat, []).append(tok)

    return {
        "categories": categories,
        "rules": rules,
        "scoring": scoring,
        "exclude_by_cat": {k: tuple(v) for k, v in exclude_by_cat.items()},
        "name_by_cat": {c["category_id"]: c["name"] for c in categories},
    }


# ---------------------------------------------------------------------------
# Matching primitives (deterministic, pure)
# ---------------------------------------------------------------------------

def _norm(text: str | None) -> str:
    """Lower-case + collapse whitespace. Deterministic, side-effect free."""
    if not text:
        return ""
    return re.sub(r"\s+", " ", str(text).lower())


@lru_cache(maxsize=8192)
def _token_re(token: str):
    """Compile (cached) a whole-token matcher for `token`.

    A token matches only when it is NOT flanked by another alphanumeric char, so
    short tokens do not match inside longer words: 'mcc' must not fire on 'mccb',
    'panel' must not fire on 'patch panel', 'dia' must not fire on 'media'. The
    boundary is alphanumeric-aware (not Python's \\b) so tokens with internal
    punctuation/spaces ('sq.mm', 'cable tray', 'c-channel') still match cleanly.
    """
    return re.compile(r"(?<![a-z0-9])" + re.escape(token) + r"(?![a-z0-9])")


def _contains(token: str, blob: str) -> bool:
    t = _norm(token)
    return bool(t) and _token_re(t).search(blob) is not None


def _tokens_present(tokens: list[str], mode: str, blob: str) -> bool:
    """True if any token matches `blob` under the given match_mode.

    any_token / phrase -> whole-token match (see _token_re) over the normalised blob.
    regex             -> re.search of each pattern (already case-insensitive blob).
    """
    if not blob:
        return False
    if mode == "regex":
        return any(re.search(p, blob, re.IGNORECASE) for p in tokens)
    return any(_contains(t, blob) for t in tokens)


def _excluded(category_id: str, ruleset: dict, desc_blob: str) -> bool:
    """True if a false-friend exclusion token for this category is present."""
    toks = ruleset["exclude_by_cat"].get(category_id, ())
    return any(_contains(t, desc_blob) for t in toks)


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------

def classify_line(
    description: str,
    ancestor_texts: list[str] | None = None,
    notes: list[str] | None = None,
    *,
    discipline: str = "Electrical",
) -> dict:
    """Classify ONE committed BoQ line into an electrical pricing category.

    Parameters
    ----------
    description : str
        The line item's own description text.
    ancestor_texts : list[str]
        The parent_node ancestor chain (preamble/line-item descriptions from the
        line up to the root). Pass the FULL chain so ancestor (section-header)
        rules can fire and so child sub-lines inherit their parent's context.
    notes : list[str]
        Attached notes for the line (attached_notes / append_notes values),
        treated as part of the line's own text for item_keyword/exclusion matching.
    discipline : str, keyword-only, default "Electrical"
        Which category ruleset to load.

    Returns
    -------
    dict with keys:
      category_id   : str  -- winning category, or 'novel' on ABSTAIN
      score         : float in [0,1] -- the (post-conflict) confidence of the winner
      band          : "HIGH" | "MED" | "LOW" | "ABSTAIN"
      signals_fired : list of {rule_id, signal_type, category_id, weight, plain}
      reason        : str  -- human-readable; composed from fired rules' `plain`,
                      and for contested results states the competing category
      runner_up     : {category_id, score} | None  -- the conflict candidate
      all_scores    : {category_id: float} -- full per-category breakdown (tuning)

    Deterministic and side-effect free: the same inputs always return the same
    output, and nothing outside the returned dict is mutated.
    """
    ruleset = load_ruleset(discipline)
    rules = ruleset["rules"]
    scoring = ruleset["scoring"]
    cap = scoring["cap"]
    bands = scoring["bands"]
    novel_id = scoring["novel_category_id"]

    desc_blob = _norm((description or "") + " " + " ".join(notes or []))
    anc_blob = _norm(" ".join(ancestor_texts or []))

    # 1-2: gather fired rules per category, summing weights + tracking signal types
    fired: list[dict] = []
    sum_by_cat: dict[str, float] = {}
    sigtypes_by_cat: dict[str, set] = {}
    for r in rules:
        stype = r.get("signal_type")
        if stype not in ("item_keyword", "ancestor"):
            continue  # exclusion rules are handled in step 4, not scored positively
        blob = desc_blob if stype == "item_keyword" else anc_blob
        if _tokens_present(r["match"], r.get("match_mode", "any_token"), blob):
            cat = r["category_id"]
            sum_by_cat[cat] = sum_by_cat.get(cat, 0.0) + float(r["weight"])
            sigtypes_by_cat.setdefault(cat, set()).add(stype)
            fired.append({
                "rule_id": r["rule_id"],
                "signal_type": stype,
                "category_id": cat,
                "weight": float(r["weight"]),
                "plain": r.get("plain", ""),
            })

    # 2-4: agreement bonus, cap, exclusions
    scores: dict[str, float] = {}
    for cat, raw in sum_by_cat.items():
        s = raw
        if len(sigtypes_by_cat.get(cat, ())) >= 2:
            s += scoring["agreement_bonus"]
        s = min(cap, s)
        if _excluded(cat, ruleset, desc_blob):
            s = 0.0
        scores[cat] = round(s, 6)

    # 5: pick top + runner-up among positive scores
    positive = {c: v for c, v in scores.items() if v > 0}
    if not positive:
        return {
            "category_id": novel_id,
            "score": 0.0,
            "band": "ABSTAIN",
            "signals_fired": [],
            "reason": "no category signal matched; routed to novel.",
            "runner_up": None,
            "all_scores": scores,
        }

    ranked = sorted(positive.items(), key=lambda kv: (-kv[1], kv[0]))
    top_cat, top_score = ranked[0]
    runner = ranked[1] if len(ranked) > 1 else None

    # 6: conflict penalty if the runner-up is a genuine competitor
    runner_up_out = None
    contested = False
    if runner and runner[1] >= top_score * scoring["conflict_margin"]:
        contested = True
        top_score = round(top_score * (1.0 - scoring["conflict_penalty"]), 6)
        runner_up_out = {"category_id": runner[0], "score": runner[1]}

    # 7: band
    if top_score >= bands["high"]:
        band = "HIGH"
    elif top_score >= bands["med"]:
        band = "MED"
    else:
        band = "LOW"

    # reason: compose the winning category's fired `plain` strings
    name_by_cat = ruleset["name_by_cat"]
    top_plains = [f["plain"] for f in fired if f["category_id"] == top_cat and f["plain"]]
    reason = " ".join(top_plains) if top_plains else f"matched {name_by_cat.get(top_cat, top_cat)}."
    if contested and runner_up_out:
        reason += (
            f" Signal is contested: this could also be "
            f"{name_by_cat.get(runner[0], runner[0])} -- review."
        )

    return {
        "category_id": top_cat,
        "score": top_score,
        "band": band,
        "signals_fired": [f for f in fired if f["category_id"] == top_cat],
        "reason": reason,
        "runner_up": runner_up_out,
        "all_scores": scores,
    }
