// The Actions cell of one handover document, in the Commission Report's style (owner 2026-09-22): one primary
// action picked by the row's STATUS, a helper line, and a ⋮ menu for the rest. The status itself is never set
// by hand -- the server derives it from what these actions do:
//
//   Pending      -> documents with something to fill: "Fill Form"
//                   From Nirmaan: "Edit" (opens the records) + "Mark as Completed"
//                   library text: "Download" + "Mark as Completed"
//   Form Filled  -> "Download" + "Mark as Completed"        (the form was saved)
//   Completed    -> the document one click away ("Edit" for From Nirmaan); "Mark as pending" undoes it
//
// NOTHING is uploaded any more (owner 2026-09-24): every document is either read live from Nirmaan or
// generated by it, so it is previewed and downloaded from this screen and then ticked off by hand.
// The signed-copy path is GONE -- no picker, no `attachment` field, nothing to view or replace.

import {
  CheckCircle2,
  Download,
  Eye,
  FileText,
  FileEdit,
  Loader2,
  MoreVertical,
  RotateCcw,
} from "lucide-react";
import * as React from "react";

import { Button } from "@/components/ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { cn } from "@/lib/utils";
import { ReportPreviewDialog } from "@/pages/CommissionReport/components/ReportPreviewDialog";

import { hodDocumentPdfUrl } from "./hodDownloads";
import type { HodDocumentMeta, HodRow } from "./types";

export interface HodActionCellProps {
  row: HodRow;
  meta: HodDocumentMeta;
  canEdit: boolean;
  /** Something is running for this row (a save, a download). */
  busy: boolean;
  /** Open the row's dialog: the form, the library text, or the From Nirmaan records. */
  onOpen: () => void;
  /** Download the document (From Nirmaan documents: the reports themselves, built on the server). */
  onDownload: () => void;
  /** From Nirmaan documents only: tick the document off by hand, or put it back to Pending. */
  onSetCompleted: (completed: boolean) => void;
}

export const HodActionCell: React.FC<HodActionCellProps> = ({
  row,
  meta,
  canEdit,
  busy,
  onOpen,
  onDownload,
  onSetCompleted,
}) => {
  const [preview, setPreview] = React.useState<{
    url: string;
    direct: boolean;
    title: string;
  } | null>(null);
  const fromApp = meta.kind === "app";
  const status = row.status;

  if (row.disabled) {
    return (
      <span className="block text-center text-[11px] text-gray-400">
        Switched off
      </span>
    );
  }

  const btn = (
    Icon: React.ElementType,
    label: string,
    onClick: () => void,
    color?: string,
    /** A reason the action is not available yet -- shown on hover, and it disables the button. */
    blocked?: string,
  ) => (
    <Button
      size="sm"
      variant={color ? "default" : "outline"}
      className={cn(
        "h-7 gap-1 px-2.5",
        color && `border-0 text-white ${color}`,
      )}
      onClick={onClick}
      disabled={busy || !!blocked}
      title={blocked || label}
    >
      {busy ? (
        <Loader2 className="h-3 w-3 animate-spin" />
      ) : (
        <Icon className="h-3 w-3" />
      )}
      <span className="text-[11px] font-medium">{label}</span>
    </Button>
  );

  const downloadBtn = btn(Download, "Download", onDownload);
  // A From Nirmaan document has no PDF of its own to hand over -- its records are ticked, saved and
  // downloaded INSIDE the dialog -- so its own button opens that dialog (owner 2026-09-24). Downloading
  // straight from the row stays in the menu, for a row whose selection is already saved.
  const editBtn = btn(FileEdit, "Edit", onOpen);
  // A From Nirmaan document is marked off AFTER its records have been reviewed (owner 2026-09-24):
  // saving the selection IS that review, so the mark waits for it. A document Nirmaan generates has
  // nothing to review -- the person is looking at the finished thing -- so it can be marked straight away.
  const reviewed = Array.isArray(row.form_data?.selected);
  const markBtn = btn(
    CheckCircle2,
    "Mark as Completed",
    () => onSetCompleted(true),
    "bg-green-600 hover:bg-green-700",
    fromApp && !reviewed
      ? "Open the records, tick what goes into the handover and Save selection first"
      : undefined,
  );

  // ---- the ⋮ menu
  type Item = {
    icon: React.ElementType;
    label: string;
    onClick: () => void;
    danger?: boolean;
  };
  const more: Item[] = [];
  if (meta.fill && status !== "Pending") {
    // A mark is a tick, not a signature: a completed document's form stays editable.
    more.push({
      icon: FileEdit,
      label: canEdit ? "Edit form" : "View form",
      onClick: onOpen,
    });
  }
  // A From Nirmaan document's own button already opens its records, so the menu does not repeat it.
  if (!meta.fill && !fromApp) {
    more.push({ icon: Eye, label: "View document", onClick: onOpen });
  }
  if (!fromApp) {
    more.push({
      icon: FileText,
      label: "Preview PDF",
      onClick: () =>
        setPreview({
          url: hodDocumentPdfUrl(row.name),
          direct: false,
          title: meta.title,
        }),
    });
  }
  if (status === "Completed") {
    more.push({
      icon: Download,
      label: fromApp ? "Download the reports" : "Download generated PDF",
      onClick: onDownload,
    });
    if (canEdit) {
      more.push({
        icon: RotateCcw,
        label: "Mark as pending",
        onClick: () => onSetCompleted(false),
      });
    }
  }

  const moreMenu = more.length > 0 && (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button
          variant="outline"
          size="icon"
          className="h-7 w-7 border-gray-300 text-slate-600"
          title="More actions"
          disabled={busy}
        >
          <MoreVertical className="h-4 w-4" />
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end" className="w-56">
        {more.map((it) => (
          <DropdownMenuItem
            key={it.label}
            onClick={it.onClick}
            className={cn("gap-2 text-xs", it.danger && "text-red-600")}
          >
            <it.icon className="h-3.5 w-3.5" /> {it.label}
          </DropdownMenuItem>
        ))}
      </DropdownMenuContent>
    </DropdownMenu>
  );

  // ---- the primary action by status
  let primary: React.ReactNode;
  let helper: string | undefined;
  if (status === "Completed") {
    // Marked off: the document stays one click away.
    primary = fromApp ? editBtn : downloadBtn;
  } else if (!canEdit) {
    primary = meta.fill
      ? btn(Eye, "View", onOpen)
      : fromApp
        ? btn(Eye, "View records", onOpen)
        : downloadBtn;
  } else if (meta.fill && status === "Pending") {
    primary = btn(
      FileText,
      "Fill Form",
      onOpen,
      "bg-blue-600 hover:bg-blue-700",
    );
  } else {
    primary = (
      <div className="flex flex-col gap-1">
        {fromApp ? editBtn : downloadBtn}
        {markBtn}
      </div>
    );
    helper = !fromApp
      ? "Preview and download the document → mark it completed"
      : reviewed
        ? "Reviewed → mark it completed"
        : "Open the records → tick and save → mark it completed";
  }

  return (
    <div className="flex w-full flex-col items-center gap-0.5">
      <div className="flex w-full items-center gap-1">
        <div className="flex flex-1 items-center justify-center gap-1">
          {primary}
        </div>
        {moreMenu}
      </div>
      {helper && (
        <span className="text-center text-[10px] leading-tight text-gray-400">
          {helper}
        </span>
      )}
      {preview && (
        <ReportPreviewDialog
          open
          onOpenChange={(o) => !o && setPreview(null)}
          pdfUrl={preview.url}
          directSrc={preview.direct}
          title={preview.title}
          fileName={`${meta.title}.pdf`}
          canDownload
        />
      )}
    </div>
  );
};
