// The Actions cell of one handover document: THREE buttons and nothing else (owner 2026-09-24).
//
//   Edit     -> opens the document: the form, or the From Nirmaan records. A LIBRARY text (O&M Manual,
//               Do's & Don'ts) does NOT get it -- its content is the library's, edited centrally in
//               Packages Settings, so a project has nothing to change (owner 2026-09-24).
//   Preview  -> the "HOD Document" print of this row, on screen. Every one of the 16 has one: a From
//               Nirmaan document prints the page that LISTS the records it hands over.
//   Download -> the same document as a file. For a From Nirmaan document that means the records
//               themselves, built on the server (with no selection saved yet, Edit opens first).
//
// The checklist answer (YES / NO / NA) is NOT here -- it is the Checklist Status column. Nothing is
// uploaded any more either: every document is read live from Nirmaan or generated by it.

import { Download, Eye, FileEdit, Loader2 } from "lucide-react";
import * as React from "react";

import { Button } from "@/components/ui/button";
import { ReportPreviewDialog } from "@/pages/CommissionReport/components/ReportPreviewDialog";

import { hodDocumentPdfUrl } from "./hodDownloads";
import { needsSaving } from "./hodRules";
import type { HodDocumentMeta, HodRow } from "./types";

export interface HodActionCellProps {
  row: HodRow;
  meta: HodDocumentMeta;
  canEdit: boolean;
  /** Something is running for this row (a save, a download). */
  busy: boolean;
  /** Open the row's dialog: the form, the library text, or the From Nirmaan records. */
  onOpen: () => void;
  /** Download the document (From Nirmaan documents: the reports themselves, built on the server). */
  onDownload: () => void;
}

export const HodActionCell: React.FC<HodActionCellProps> = ({
  row,
  meta,
  canEdit,
  busy,
  onOpen,
  onDownload,
}) => {
  const [preview, setPreview] = React.useState(false);

  if (row.disabled) {
    return (
      <span className="block text-center text-[11px] text-gray-400">
        Switched off
      </span>
    );
  }

  const btn = (
    Icon: React.ElementType,
    label: string,
    onClick: () => void,
    /** Only the download runs a job, so only it shows the row's spinner. */
    spins = false,
  ) => (
    <Button
      size="sm"
      variant="outline"
      className="h-7 gap-1 px-2"
      onClick={onClick}
      disabled={busy}
      title={label}
    >
      {busy && spins ? (
        <Loader2 className="h-3 w-3 animate-spin" />
      ) : (
        <Icon className="h-3 w-3" />
      )}
      <span className="text-[11px] font-medium">{label}</span>
    </Button>
  );

  return (
    <div className="flex items-center justify-center gap-1">
      {needsSaving(meta) && btn(FileEdit, canEdit ? "Edit" : "View", onOpen)}
      {btn(Eye, "Preview", () => setPreview(true))}
      {btn(Download, "Download", onDownload, true)}

      {preview && (
        <ReportPreviewDialog
          open
          onOpenChange={(o) => !o && setPreview(false)}
          pdfUrl={hodDocumentPdfUrl(row.name)}
          directSrc={false}
          title={meta.title}
          fileName={`${meta.title}.pdf`}
          canDownload
        />
      )}
    </div>
  );
};
