import React from 'react';
import { MapPin, MessagesSquare } from 'lucide-react';
import { cn } from '@/lib/utils';

interface ImageData {
  image_link: string;
  location?: string;
  latitude?: number;
  longitude?: number;
  remarks?: string;
}

interface PDFImageGridProps {
  images: ImageData[];
  maxImagesPerPage?: number;
}

/**
 * PDF-optimized Image Grid Component
 *
 * Unlike ImageBentoGrid, this component does NOT use async state management.
 * Images are rendered directly without pre-loading, which ensures they appear
 * in PDFs generated by react-to-print.
 *
 * Key differences from ImageBentoGrid:
 * - No useState/useEffect (synchronous rendering)
 * - No loading states (immediate render)
 * - Uses object-contain to prevent stretching
 * - Fixed grid layout optimized for PDF printing
 */
export const PDFImageGrid: React.FC<PDFImageGridProps> = ({
  images,
  maxImagesPerPage = 4,
}) => {
  if (!images || images.length === 0) {
    return (
      <div className="w-full h-32 bg-gray-100 flex items-center justify-center text-gray-500 rounded-lg border-2 border-dashed border-gray-300">
        <p className="text-base font-medium">No Work Images Available</p>
      </div>
    );
  }

  // Split images into pages
  const pages: ImageData[][] = [];
  for (let i = 0; i < images.length; i += maxImagesPerPage) {
    pages.push(images.slice(i, i + maxImagesPerPage));
  }

  return (
    <>
      {pages.map((pageImages, pageIdx) => (
        <PDFImageGridPage
          key={pageIdx}
          images={pageImages}
          pageNumber={pageIdx + 1}
          totalPages={pages.length}
        />
      ))}
    </>
  );
};

/**
 * Single page of PDF Image Grid
 */
const PDFImageGridPage: React.FC<{
  images: ImageData[];
  pageNumber: number;
  totalPages: number;
}> = ({ images, pageNumber, totalPages }) => {
  return (
    <div className={cn(
      "grid grid-cols-2 gap-4",
      pageNumber > 1 && "page-break-before"
    )}>
      {images.map((image, idx) => (
        <div
          key={idx}
          className="rounded-lg overflow-hidden shadow-md bg-white border border-gray-200 avoid-page-break-inside"
        >
          <div className="flex flex-col h-full">
            {/* Image container with fixed aspect ratio */}
            <div className="w-full bg-gray-50 flex items-center justify-center" style={{ minHeight: '200px' }}>
              <img
                src={image.image_link}
                alt={`Work Image ${(pageNumber - 1) * 4 + idx + 1}`}
                className="w-full h-full object-contain max-h-[250px]"
                style={{
                  imageRendering: 'auto',
                  display: 'block',
                }}
              />
            </div>

            {/* Details section */}
            <div className="w-full p-2 flex flex-col justify-between">
              {/* Location */}
              <div className="flex items-start text-xs text-gray-700 mb-2">
                <MapPin className="h-3 w-3 mr-1 mt-0.5 text-red-500 flex-shrink-0" />
                <span className="font-medium break-words line-clamp-2">
                  {image.location ||
                    `Lat: ${image.latitude?.toFixed(2) || 'N/A'}, Lon: ${image.longitude?.toFixed(2) || 'N/A'}`}
                </span>
              </div>

              {/* Remarks */}
              <div className="bg-yellow-100 text-yellow-900 rounded-md p-1.5 break-words">
                <div className="flex items-start text-xs">
                  <MessagesSquare className="h-3 w-3 mr-1 mt-0.5 flex-shrink-0" />
                  <span className="line-clamp-3">
                    {image.remarks || "No remarks provided."}
                  </span>
                </div>
              </div>
            </div>
          </div>
        </div>
      ))}
    </div>
  );
};
